language: java
addons:
  mariadb: '10.0'
jdk:
  - oraclejdk8
before_script:
  - mysql -e "use mysql; update user set password=PASSWORD('123456') where User='root'; flush privileges;" -uroot
  - mysql -uroot -p123456 < testsql/unielwin_course.sql
  - mysql -uroot -p123456 < testsql/unielwin_prof.sql
  - mysql -uroot -p123456 < testsql/unielwin_RA.sql
  - mysql -uroot -p123456 < testsql/unielwin_registration.sql
  - mysql -uroot -p123456 < testsql/unielwin_student.sql
  - mysql -uroot -p123456 < testsql/Mutagenesis_std_Atom.sql
  - mysql -uroot -p123456 < testsql/Mutagenesis_std_bond.sql
  - mysql -uroot -p123456 < testsql/Mutagenesis_std_Mole.sql
  - mysql -uroot -p123456 < testsql/Mutagenesis_std_moleatm.sql
script: 
  - cd jar
  - java -jar FactorBase.jar > jar.txt
  - tail jar.txt
  - ls -lh
  - tail dag_.txt
  - java -jar MLNExporter.jar > mln_jar.txt
  - tail mln_jar.txt
  - cd ../src/
  - javac -cp ".:./lib/*" Config.java BZScriptRunner.java MakeSetup.java
  - javac -cp ".:./lib/*" RunBB.java
  - javac -cp ".:./lib/*" RelationalClassification.java
  - java -cp ".:./lib/*" MakeSetup > a.txt
  - java -cp ".:./lib/*" RunBB > b.txt
  - java -cp ".:./lib/*" RelationalClassifcation.java > c.txt
  - tail a.txt
  - tail b.txt
  - tail c.txt
  - cd ../
after_script:
  - mysql -e "show databases;" -uroot -p123456
  - mysql -e "use unielwin_BN; show tables;" -uroot -p123456
  - mysql -e "use unielwin_CT; show tables;" -uroot -p123456
  - mysql -e "use Mutagenesis_std_target_final_CT; show tables;" -uroot -p123456
  - mysql -e "use Mutagenesis_std_target_final; show tables;" -uroot -p123456
  - mysql -e "use Mutagenesis_std_target_CT; show tables;" -uroot -p123456
  - mysql -e "use Mutagenesis_std_target_BN; show tables;" -uroot -p123456
  - mysql -e "use Mutagenesis_std_target; show tables;" -uroot -p123456
